//Auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";
//Movies
export const ADD_FAVORITE_MOVIE = "ADD_FAVORITE_MOVIE";
export const DELETE_FAVORITE_MOVIE = "DELETE_FAVORITE_MOVIE";
export const GET_NOW_PLAYING_MOVIES = "GET_NOW_PLAYING_MOVIES";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const GET_FAVORITE_MOVIES = "GET_FAVORITE_MOVIES";
export const GET_MOVIE_VIDEO = "GET_MOVIE_VIDEO";
